version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - database
  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    volumes:
      - db_data:/var/lib/postgresql/data/
volumes:
  db_data:
